### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by Fodilahy-mena**
Hello team, would you mind taking a look at this pull request?
Thanks

### CODE REVIEW

**Comment by constantingoeldel** [comment]
Fix bugs with the description `This task is done and needs a review.` is not a descriptive PR. This would be rejected instantly in other companies. Please change this or close this pull request

**Review by andrzej-onja — APPROVED** [review]

**Review by andrzej-onja — CHANGES_REQUESTED** [review]
feat(Home screen): Adds list of categories 
Adds list item component
Adds list item component stories
Creates fetch function and adds it to utils
Refs: ticketxxID

**Review by andrzej-onja — APPROVED** [review]

**Comment by andrzej-onja** [comment]
> Fix bugs with the description `This task is done and needs a review.` is not a descriptive PR. This would be rejected instantly in other companies. Please change this or close this pull request

good point Please raise another pull request with different branch name like primary-language-fix

**Comment by Fodilahy-mena** [comment]
This pull request has been closed due to naming issue. You can see the newer version of it here in fix-native-language branch https://github.com/onja-org/malagasy-rn-Polonium/pull/6

**Pull request closed without merging**
